services:
  neuralearn:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    image: neuralearn
    container_name: neuralearn-app
    ports:
      - "4000:3000"
    env_file:
      - .env.local
    environment:
      - CI=true
    volumes:
      - .:/app
      - node_modules-brain-graph:/app/node_modules

volumes:
  node_modules-brain-graph: